version: '3'
services:
  launchbi:
    image: nginx:stable-alpine
    volumes:
      # MAPEAMENTO DIRETO: Pega a pasta dist do Git e coloca no Nginx
      - ./dist:/usr/share/nginx/html
    networks:
      - ruliannet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.launchbi.rule=Host(`dashboard.rulianmedeiros.com`)"
      - "traefik.http.routers.launchbi.entrypoints=websecure"
      - "traefik.http.routers.launchbi.tls=true"

networks:
  ruliannet:
    external: true