services:
  db_bi:
    image: postgres:15
    container_name: postgres_bi_launch
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bi_lancamento
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data