version: '3.8'
services:
  launchbi:
    build: .
    container_name: launchbi_app
    networks:
      - ruliannet # Sua rede existente na Hetzner
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.launchbi.rule=Host(`dashboard.rulianmedeiros.com`)"
      - "traefik.http.routers.launchbi.entrypoints=websecure"
      - "traefik.http.routers.launchbi.tls=true"

networks:
  ruliannet:
    external: true