version: '3'
services:
  launchbi:
    image: nginx:alpine
    container_name: launchbi_app
    volumes:
      # O Nginx precisa ler de dentro da pasta dist que vocÃª enviou
      - ./dist:/usr/share/nginx/html
    networks:
      - ruliannet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.launchbi.rule=Host(`dashboard.rulianmedeiros.com`)"
      - "traefik.http.routers.launchbi.entrypoints=websecure"
      - "traefik.http.routers.launchbi.tls=true"

networks:
  ruliannet:
    external: true